import { MarketplaceItem } from './data';
import { QuizQuestion } from '@/types/quiz';
import { shuffleArray } from '@/utils/shuffle';

const createQuestion = (q: string, opts: string[], ans: string): QuizQuestion => ({
    question: q,
    options: opts,
    answer: ans,
    type: 'multiple',
});

const grandMockQuestions: QuizQuestion[] = [
    // --- PSYCHOLOGICAL ASSESSMENT (25) ---
    createQuestion("If the Variance is 16, what is the Standard Deviation?", ["4", "8", "256", "2"], "4"),
    createQuestion("Correlating a test with a future criterion measures:", ["Predictive Validity", "Concurrent Validity", "Construct Validity", "Content Validity"], "Predictive Validity"),
    createQuestion("An item difficulty (p) of 0.20 suggests the item is:", ["Difficult", "Easy", "Average", "Invalid"], "Difficult"),
    createQuestion("In the Stanine system (Mean=5, SD=2), a score of 7 is", ["Above Average", "Average", "Superior", "Below Average"], "Above Average"),
    createQuestion("A Psychologist having a sexual relationship with a former client is:", ["Prohibited for at least 2 years after termination", "Always allowed", "Never allowed", "Allowed immediately"], "Prohibited for at least 2 years after termination"),
    createQuestion("Test security is the primary responsibility of:", ["The Psychometrician/Psychologist", "The Publisher", "The Client", "The Government"], "The Psychometrician/Psychologist"),
    createQuestion("The Exner Comprehensive System is used for scoring the:", ["Rorschach Inkblot Test", "TAT", "MMPI", "Bender-Gestalt"], "Rorschach Inkblot Test"),
    createQuestion("Percentile Rank belongs to which level of measurement?", ["Ordinal", "Interval", "Ratio", "Nominal"], "Ordinal"),
    createQuestion("Coefficient Alpha estimates reliability based on:", ["Internal Consistency", "Stability", "Time sampling", "Rater agreement"], "Internal Consistency"),
    createQuestion("As Reliability increases, the Standard Error of Measurement (SEM):", ["Decreases", "Increases", "Stays the same", "Becomes zero"], "Decreases"),
    createQuestion("Temperature in Celsius is an example of:", ["Interval scale", "Ratio scale", "Ordinal scale", "Nominal scale"], "Interval scale"),
    createQuestion("A test measuring what you have learned in school is:", ["Achievement Test", "Aptitude Test", "Intelligence Test", "Personality Test"], "Achievement Test"),
    createQuestion("The Flynn Effect suggests that over time:", ["IQ scores increase", "IQ scores decrease", "IQ stays stable", "Verbal IQ increases but Performance decreases"], "IQ scores increase"),
    createQuestion("Believing a generic horoscope describes you perfectly is the:", ["Barnum Effect", "Halo Effect", "Placebo Effect", "Flynn Effect"], "Barnum Effect"),
    createQuestion("Taking the same test twice improves score due to:", ["Practice Effects", "Fatigue", "Regression to mean", "Maturation"], "Practice Effects"),
    createQuestion("When can you release raw test data to a client?", ["Never / Discouraged", "Always", "If they pay", "If they ask nicely"], "Never / Discouraged"),
    createQuestion("Which is NOT an exception to confidentiality?", ["Client request for own records (with caveats)", "Imminent harm to self/others", "Court Order", "Client's boss asks for it"], "Client's boss asks for it"),
    createQuestion("Utility analysis in testing refers to:", ["Cost-effectiveness and benefits", "How easy it is to score", "Computerization", "Statistical power"], "Cost-effectiveness and benefits"),
    createQuestion("High correlation with an established valid test is evidence of:", ["Convergent Validity", "Divergent Validity", "Reliability", "Face Validity"], "Convergent Validity"),
    createQuestion("In Factor Analysis, 'Orthogonal Rotation' keeps factors:", ["Uncorrelated (Independent)", "Correlated", "Oblique", "Overlapping"], "Uncorrelated (Independent)"),
    createQuestion("A negative Discrimination Index means:", ["Low scorers got it right, High scorers got it wrong", "Item is good", "Item is too hard", "Item is too easy"], "Low scorers got it right, High scorers got it wrong"),
    createQuestion("A test with items of increasing difficulty and no time limit is a:", ["Power Test", "Speed Test", "Performance Test", "Projective Test"], "Power Test"),
    createQuestion("Interpreting a score based on a fixed standard (e.g., 75% passing):", ["Criterion-Referenced", "Norm-Referenced", "Ipsative", "Objective"], "Criterion-Referenced"),
    createQuestion("Split-Half reliability divides the test by:", ["Odd and Even items", "First and Second half", "Randomly", "Difficulty"], "Odd and Even items"),
    createQuestion("Computer-based test interpretations should be viewed as:", ["Consultations/Hypotheses", "Final diagnoses", "Absolute truth", "Medical advice"], "Consultations/Hypotheses"),

    // --- THEORIES OF PERSONALITY (25) ---
    createQuestion("Freud: 'Cathexis' is the investment of energy; 'Anticathexis' is:", ["Blocking/Inhibiting energy", "Releasing energy", "Dreaming", "Sublimation"], "Blocking/Inhibiting energy"),
    createQuestion("Jung's symbol of the Self/Wholeness:", ["Mandala", "Cross", "Circle", "Snake"], "Mandala"),
    createQuestion("Adler's concept of 'Masculine Protest' applies to:", ["Both men and women", "Men only", "Women only", "Children only"], "Both men and women"),
    createQuestion("Horney: The 'Tyranny of the Shoulds' leads to:", ["Self-hatred and rigidity", "Self-actualization", "Flexibility", "Social interest"], "Self-hatred and rigidity"),
    createQuestion("Erikson's 'Epigenetic Principle' states that:", ["Development occurs in a predetermined sequence", "Genes control everything", "Environment is key", "Personality is random"], "Development occurs in a predetermined sequence"),
    createQuestion("Melanie Klein's position characterized by fear of persecution:", ["Paranoid-Schizoid Position", "Depressive Position", "Autistic Position", "Symbiotic Position"], "Paranoid-Schizoid Position"),
    createQuestion("Winnicott's 'Good Enough Mother':", ["Adapts to infant's needs but gradually fails", "Is perfect", "Never fails", "Is neglectful"], "Adapts to infant's needs but gradually fails"),
    createQuestion("Rogers: The internal guide that tells us what feels right:", ["Organismic Valuing Process", "Superego", "Ideal Self", "Conditions of Worth"], "Organismic Valuing Process"),
    createQuestion("Maslow: Needs arising from a lack/deficiency:", ["D-Needs", "B-Needs", "Metaneeds", "Self-Actualization"], "D-Needs"),
    createQuestion("Rollo May: The 'Daimonic' is:", ["Any natural function which has the power to take over the whole person", "Evil spirits", "Psychosis", "Creativity only"], "Any natural function which has the power to take over the whole person"),
    createQuestion("Frankl: 'Sunday Neurosis' refers to:", ["Depression when busy week stops and meaninglessness hits", "Religious guilt", "Fear of church", "Weekly anxiety"], "Depression when busy week stops and meaninglessness hits"),
    createQuestion("Bandura: Learning by watching others be rewarded:", ["Vicarious Reinforcement", "Self-Reinforcement", "Punishment", "Extinction"], "Vicarious Reinforcement"),
    createQuestion("Skinner: The schedule producing a 'scalloped' response pattern:", ["Fixed Interval", "Fixed Ratio", "Variable Interval", "Variable Ratio"], "Fixed Interval"),
    createQuestion("Rotter: Beliefs that apply across many situations:", ["Generalized Expectancies", "Specific Expectancies", "Reinforcement Value", "Locus of Control"], "Generalized Expectancies"),
    createQuestion("Mischel's 'Consistency Paradox':", ["Intuition says personality is consistent, but data shows it varies", "Personality is always consistent", "Behavior is random", "Traits don't exist"], "Intuition says personality is consistent, but data shows it varies"),
    createQuestion("Allport: Motives becoming independent of their origins:", ["Functional Autonomy", "Proprium", "Sublimation", "Reaction Formation"], "Functional Autonomy"),
    createQuestion("Cattell: Intelligence that is innate/biological:", ["Fluid Intelligence", "Crystallized Intelligence", "g factor", "s factor"], "Fluid Intelligence"),
    createQuestion("Eysenck associated Introversion with:", ["High Reticular Activating System (RAS) arousal", "Low RAS arousal", "High Dopamine", "Low Serotonin"], "High Reticular Activating System (RAS) arousal"),
    createQuestion("McCrae & Costa: Fantasy, Aesthetics, Feelings are facets of:", ["Openness", "Conscientiousness", "Extraversion", "Agreeableness"], "Openness"),
    createQuestion("Kelly: 'Persons differ from each other in their construction of events':", ["Individuality Corollary", "Construction Corollary", "Choice Corollary", "Range Corollary"], "Individuality Corollary"),
    createQuestion("Sikolohiyang Pilipino: 'Pakikiramdam' is best described as:", ["A pivotal interpersonal value / shared inner perception", "A superstition", "Gossiping", "Feeling sick"], "A pivotal interpersonal value / shared inner perception"),
    createQuestion("SP: 'Puri' is external honor; 'Dangal' is:", ["Internal honor/dignity", "Wealth", "Social Status", "Physical beauty"], "Internal honor/dignity"),
    createQuestion("SP: 'Bahala na' reflects:", ["Determination and risk-taking", "Fatalism only", "Laziness", "Surrender"], "Determination and risk-taking"),
    createQuestion("SP: Using a go-between to avoid conflict:", ["Pamamagitan", "Parinig", "Pakikisama", "Tampo"], "Pamamagitan"),
    createQuestion("Enriquez criticized the western view of 'Pikon' as:", ["Ignoring the cultural context of teasing", "A mental disorder", "Aggression", "Low IQ"], "Ignoring the cultural context of teasing"),

    // --- ABNORMAL PSYCHOLOGY (25) ---
    createQuestion("Schizophrenia: Poverty of speech is called:", ["Alogia", "Avolition", "Anhedonia", "Asociality"], "Alogia"),
    createQuestion("Schizoaffective Disorder requires mood symptoms for:", ["Majority of the total duration of the illness", "1 week", "2 days", "Only during psychosis"], "Majority of the total duration of the illness"),
    createQuestion("Bipolar I Manic Episode minimum duration:", ["1 week (or hospitalization)", "4 days", "2 weeks", "1 month"], "1 week (or hospitalization)"),
    createQuestion("Bipolar II Hypomanic Episode minimum duration:", ["4 days", "1 week", "2 weeks", "2 days"], "4 days"),
    createQuestion("Cyclothymia is to Bipolar as Dysthymia is to:", ["Major Depression", "Schizophrenia", "Anxiety", "Panic"], "Major Depression"),
    createQuestion("Panic Disorder symptoms include:", ["Palpitations, sweating, trembling, fear of dying", "Hallucinations", "Memory loss", "Sleepiness"], "Palpitations, sweating, trembling, fear of dying"),
    createQuestion("Agoraphobia without Panic Disorder:", ["Is now a distinct diagnosis in DSM-5", "Does not exist", "Is rare", "Is part of GAD"], "Is now a distinct diagnosis in DSM-5"),
    createQuestion("Social Anxiety Disorder 'Performance only' usually applies to:", ["Public speaking / Musicians", "Eating in public", "Using public toilets", "Dating"], "Public speaking / Musicians"),
    createQuestion("OCD obsessions are:", ["Intrusive and ego-dystonic (unwanted)", "Ego-syntonic (enjoyed)", "Delusional", "Realistic worries"], "Intrusive and ego-dystonic (unwanted)"),
    createQuestion("Hoarding Disorder is primarily a safety hazard due to:", ["Fire risk and blocking exits", "Bacteria", "Thieves", "Dust"], "Fire risk and blocking exits"),
    createQuestion("PTSD 'Dissociative' specifier involves:", ["Depersonalization / Derealization", "Amnesia only", "Fugue", "Violence"], "Depersonalization / Derealization"),
    createQuestion("Acute Stress Disorder becomes PTSD after:", ["1 month", "3 months", "6 months", "1 year"], "1 month"),
    createQuestion("Somatic Symptom Disorder vs Illness Anxiety:", ["SSD has actual somatic symptoms; IAD has minimal/none", "They are the same", "IAD has pain", "SSD is faking"], "SSD has actual somatic symptoms; IAD has minimal/none"),
    createQuestion("Conversion Disorder's 'La Belle Indifference':", ["Lack of concern about the symptom", "Extreme distress", "Anger", "Panic"], "Lack of concern about the symptom"),
    createQuestion("Malingering differs from Factitious Disorder by:", ["Presence of external incentive (money, legal)", "Need for attention", "Unconscious motivation", "Childhood trauma"], "Presence of external incentive (money, legal)"),
    createQuestion("Anorexia Nervosa types:", ["Restricting and Binge-Eating/Purging", "Type 1 and 2", "Mild and Severe", "Child and Adult"], "Restricting and Binge-Eating/Purging"),
    createQuestion("Bulimia Nervosa binge/purge frequency:", ["At least once a week for 3 months", "Daily", "Once a month", "Twice a year"], "At least once a week for 3 months"),
    createQuestion("Gender Dysphoria duration:", ["At least 6 months", "1 month", "2 years", "Lifetime"], "At least 6 months"),
    createQuestion("Paraphilic Disorders are only diagnosed when:", ["There is distress, impairment, or harm to others", "Any fetish exists", "Unusual sex occurs", "Society disapproves"], "There is distress, impairment, or harm to others"),
    createQuestion("Cluster A Personality Disorder (Paranoid) main feature:", ["Distrust and suspiciousness", "Emotionality", "Anxiety", "Psychosis"], "Distrust and suspiciousness"),
    createQuestion("Borderline Personality Disorder core fear:", ["Abandonment", "Failure", "Spiders", "Germs"], "Abandonment"),
    createQuestion("Histrionic speech style:", ["Impressionistic and lacking detail", "Exact and precise", "Slow", "Scientific"], "Impressionistic and lacking detail"),
    createQuestion("Narcissistic Personality Disorder self-esteem is:", ["Fragile", "High and stable", "Non-existent", "Healthy"], "Fragile"),
    createQuestion("Avoidant vs Schizoid: Avoidant desires:", ["Social connection but fears rejection", "Solitude", "Pain", "Attention"], "Social connection but fears rejection"),
    createQuestion("OCPD main feature:", ["Perfectionism interfering with task completion", "Checking locks", "Hearing voices", "Fear of fat"], "Perfectionism interfering with task completion"),

    // --- IO PSYCHOLOGY (25) ---
    createQuestion("Job Analysis resource 'O*NET' uses:", ["Worker-oriented and Job-oriented descriptors", "Only tasks", "Only salaries", "History"], "Worker-oriented and Job-oriented descriptors"),
    createQuestion("Critical Incident Technique collects:", ["Specific behaviors leading to success/failure", "General opinions", "Ratings", "Complaints"], "Specific behaviors leading to success/failure"),
    createQuestion("Low Selection Ratio means:", ["Selectivity is high (few hired from many)", "Selectivity is low", "Test is useless", "Hire everyone"], "Selectivity is high (few hired from many)"),
    createQuestion("A 'False Positive' in selection is:", ["Hiring someone who fails", "Rejecting a good candidate", "Hiring a star", "Rejecting a failure"], "Hiring someone who fails"),
    createQuestion("Behavioral Interview question example:", ["Tell me about a time you handled conflict...", "What would you do if...", "Do you like conflict?", "Are you angry?"], "Tell me about a time you handled conflict..."),
    createQuestion("Assessment Center technique 'Leaderless Group Discussion' observes:", ["Interpersonal and leadership skills", "Writing skills", "Math skills", "Typing"], "Interpersonal and leadership skills"),
    createQuestion("Massed Practice vs Distributed Practice: Which is better for retention?", ["Distributed Practice", "Massed Practice", "Both equal", "Neither"], "Distributed Practice"),
    createQuestion("Kirkpatrick Level 4 measures:", ["Results / ROI", "Reaction", "Learning", "Behavior"], "Results / ROI"),
    createQuestion("Paired Comparison appraisal method:", ["Compares every employee with every other employee", "Ranks top to bottom", "Rates on scale 1-5", "Essays"], "Compares every employee with every other employee"),
    createQuestion("Rater Error 'Central Tendency':", ["Rating everyone in the middle", "Rating everyone high", "Rating everyone low", "Rating based on recency"], "Rating everyone in the middle"),
    createQuestion("360-degree feedback is best used for:", ["Developmental purposes", "Salary decisions", "Firing", "Recruitment"], "Developmental purposes"),
    createQuestion("ERG Theory differs from Maslow by:", ["Frustration-Regression principle", "No hierarchy", "5 levels", "Focus on power"], "Frustration-Regression principle"),
    createQuestion("Herzberg's Hygiene Factors are related to:", ["Job Context (Pay, Conditions)", "Job Content (Achievement)", "Personality", "Intelligence"], "Job Context (Pay, Conditions)"),
    createQuestion("Goal Setting: Feedback is:", ["Crucial for goals to be effective", "Optional", "Distracting", "Harmful"], "Crucial for goals to be effective"),
    createQuestion("Equity Theory: Response to Underpayment Inequity:", ["Lower inputs or ask for raise", "Work harder", "Feel guilty", "Donate money"], "Lower inputs or ask for raise"),
    createQuestion("Fiedler's LPC measures:", ["Least Preferred Coworker (Leader style)", "Productivity", "Loyalty", "Competence"], "Least Preferred Coworker (Leader style)"),
    createQuestion("Transformational Leadership 'Intellectual Stimulation':", ["Encouraging creativity and challenging assumptions", "Giving money", "Giving orders", "Being friendly"], "Encouraging creativity and challenging assumptions"),
    createQuestion("Organizational Culture 'Artifacts':", ["Visible structures and processes (dress, layout)", "Values", "Assumptions", "Thoughts"], "Visible structures and processes (dress, layout)"),
    createQuestion("OD Intervention 'Survey Feedback':", ["Collect data -> Feed back to employees -> Plan action", "Secret survey", "Feedback to CEO only", "Firing based on survey"], "Collect data -> Feed back to employees -> Plan action"),
    createQuestion("Social Facilitation:", ["Performance improves in presence of others (for simple tasks)", "Performance drops", "People get lazy", "People fight"], "Performance improves in presence of others (for simple tasks)"),
    createQuestion("Role Conflict:", ["Incompatible demands", "Unclear demands", "Too much work", "Too little work"], "Incompatible demands"),
    createQuestion("Burnout dimension 'Depersonalization':", ["Cynicism and detachment from people", "Exhaustion", "Low accomplishment", "Depression"], "Cynicism and detachment from people"),
    createQuestion("Flextime benefits:", ["Work-life balance and reduced lateness", "Higher pay", "Less work", "More meetings"], "Work-life balance and reduced lateness"),
    createQuestion("Ergonomics 'Anthropometry':", ["Body measurements", "Muscle strength", "Eye sight", "Hearing"], "Body measurements"),
    createQuestion("Brand Loyalty in Consumer Psych:", ["Repeat purchasing and preference", "Buying cheapest", "Buying random", "Hating brands"], "Repeat purchasing and preference"),
];

export const grandMock2026Item: MarketplaceItem = {
    id: 'grand-mock-2026-final',
    title: 'Grand Mock Board Exam 2026 (100 New Items)',
    description: 'The ultimate final coaching mock exam. 100 highly curated, mixed questions across all 4 subjects with randomized order.',
    category: 'Education',
    author: 'Cerebrum Master',
    downloads: 0,
    rating: 5.0,
    price: 'Premium',
    content: shuffleArray(grandMockQuestions)
};
