import { MarketplaceItem } from './data';
import { QuizQuestion } from '@/types/quiz';
import { shuffleArray } from '@/utils/shuffle';

const createQuestion = (q: string, opts: string[], ans: string): QuizQuestion => ({
    question: q,
    options: opts,
    answer: ans,
    type: 'multiple',
});

const ioPsychQuestions: QuizQuestion[] = [
    // 1. Recruitment, Selection & Placement (Approx 20)
    createQuestion("The process of searching for and obtaining qualified job candidates is:", ["Recruitment", "Selection", "Placement", "Training"], "Recruitment"),
    createQuestion("Which 'cut-off' approach requires a candidate to pass each test in a battery?", ["Multiple Cut-off", "Multiple Hurdle", "Multiple Regression", "Profile Matching"], "Multiple Hurdle"),
    createQuestion("RJP stands for:", ["Realistic Job Preview", "Random Job Placement", "Real Job Performance", "Rapid Job Promotion"], "Realistic Job Preview"),
    createQuestion("The degree to which a selection device actually measures what it claims to measure:", ["Validity", "Reliability", "Utility", "Fairness"], "Validity"),
    createQuestion("Adverse Impact is often determined by the:", ["4/5ths Rule (80% Rule)", "50% Rule", "Quota System", "Standard Deviation"], "4/5ths Rule (80% Rule)"),
    createQuestion("Which interview type has the highest validity?", ["Structured Interview", "Unstructured Interview", "Stress Interview", "Group Interview"], "Structured Interview"),
    createQuestion("Assessment Centers are primarily used for:", ["Managerial Selection/Promotion", "Clerical hiring", "Firing decisions", "Blue-collar worker testing"], "Managerial Selection/Promotion"),
    createQuestion("The 'In-Basket' technique simulates:", ["Managerial administrative tasks", "Physical labor", "Group discussion", "Coding skills"], "Managerial administrative tasks"),
    createQuestion("Biodata refers to:", ["Biographical Information", "Biological samples", "Medical history", "Fingerprints"], "Biographical Information"),
    createQuestion("Which selection error involves hiring a candidate who performs poorly?", ["False Positive", "False Negative", "True Positive", "True Negative"], "False Positive"),
    createQuestion("The 'Halo Effect' in interviews occurs when:", ["One positive characteristic influences the total evaluation", "The interviewer is strict", "The candidate is late", "The interviewer talks too much"], "One positive characteristic influences the total evaluation"),
    createQuestion("Graphology (Handwriting Analysis) is considered:", ["scientifically invalid for selection", "High validity", "Moderate validity", "Essential"], "scientifically invalid for selection"),
    createQuestion("Negligent Hiring is:", ["Hiring someone who poses a risk without checking background", "Hiring too slowly", "Hiring untalented people", "Firing without cause"], "Hiring someone who poses a risk without checking background"),
    createQuestion("KSAOs stands for:", ["Knowledge, Skills, Abilities, and Other characteristics", "Knowledge, Strategy, Aptitude, Organization", "Key Skills and Options", "None of the above"], "Knowledge, Skills, Abilities, and Other characteristics"),
    createQuestion("Job Analysis outcome that lists the tasks and duties:", ["Job Description", "Job Specification", "Job Evaluation", "Performance Appraisal"], "Job Description"),
    createQuestion("Job Analysis outcome that lists the human requirements:", ["Job Specification", "Job Description", "Job Design", "Job Rotation"], "Job Specification"),
    createQuestion("Which method of Job Analysis involves the worker keeping a log?", ["Work Diaries/Logs", "Observation", "Interview", "Questionnaire"], "Work Diaries/Logs"),
    createQuestion("The Critical Incident Technique focuses on:", ["Specific behaviors that lead to success or failure", "Average performance", "Traits", "General duties"], "Specific behaviors that lead to success or failure"),
    createQuestion("Person-Organization Fit refers to:", ["Compatibility between employee values and company culture", "Skill match only", "Salary match", "Location match"], "Compatibility between employee values and company culture"),
    createQuestion("Headhunters are typically used for:", ["Executive/Specialized search", "Entry-level jobs", "Mass hiring", "Interns"], "Executive/Specialized search"),

    // 2. Training & Development (Approx 15)
    createQuestion("The first step in the Training Cycle is:", ["Training Needs Analysis", "Design", "Implementation", "Evaluation"], "Training Needs Analysis"),
    createQuestion("Which analysis determines WHO needs training?", ["Person Analysis", "Task Analysis", "Organizational Analysis", "Market Analysis"], "Person Analysis"),
    createQuestion("Social Learning Theory (Bandura) emphasizes:", ["Modeling/Observational Learning", "Rote memorization", "Punishment", "Lectures"], "Modeling/Observational Learning"),
    createQuestion("Distributed Practice is:", ["Spaced out over time", "Crammed in one session", "Done at home", "Done online"], "Spaced out over time"),
    createQuestion("Transfer of Training means:", ["Applying learned skills to the actual job", "Moving to a new department", "Promoting the trainer", "Repeating the course"], "Applying learned skills to the actual job"),
    createQuestion("Kirkpatrick's Level 2 Evaluation measures:", ["Learning", "Reaction", "Behavior", "Results"], "Learning"),
    createQuestion("Kirkpatrick's Level 3 Evaluation measures:", ["Behavior (Transfer)", "Reaction", "Learning", "Results"], "Behavior (Transfer)"),
    createQuestion("On-the-Job Training (OJT) advantage:", ["High transfer of training", "Low cost", "No disruption", "Standardized"], "High transfer of training"),
    createQuestion("Vestibule Training is:", ["Simulation in a separate area closer to actual job conditions", "Classroom lecture", "Apprenticeship", "Mentoring"], "Simulation in a separate area closer to actual job conditions"),
    createQuestion("Behavior Modeling Training involves:", ["Watching a model -> Rehearsing -> Feedback", "Reading a book", "Listening to a lecture", "Taking a test"], "Watching a model -> Rehearsing -> Feedback"),
    createQuestion("Job Rotation is:", ["Moving employees between different jobs", "Firing employees", "Rotating shifts only", "Changing desk position"], "Moving employees between different jobs"),
    createQuestion("Mentoring is typically:", ["Long-term relationship for career growth", "Short-term skill instruction", "Group training", "Online course"], "Long-term relationship for career growth"),
    createQuestion("Coaching is typically:", ["Task/Performance focused", "Therapy", "Friendship", "General advice"], "Task/Performance focused"),
    createQuestion("Gamification in training uses:", ["Game mechanics to increase engagement", "Board games only", "Video games for fun", "Gambling"], "Game mechanics to increase engagement"),
    createQuestion("ROI in training stands for:", ["Return on Investment", "Rate of Interest", "Risk of Injury", "Range of Improvement"], "Return on Investment"),

    // 3. Performance Appraisal & Management (Approx 15)
    createQuestion("360-Degree Feedback involves ratings from:", ["Supervisors, peers, subordinates, and self", "Boss only", "Customers only", "HR only"], "Supervisors, peers, subordinates, and self"),
    createQuestion("Central Tendency Error is:", ["Rating everyone as average", "Rating everyone high", "Rating everyone low", "Rating based on one trait"], "Rating everyone as average"),
    createQuestion("Leniency Error is:", ["Rating everyone higher than deserved", "Rating everyone average", "Rating everyone low", "Strictness"], "Rating everyone higher than deserved"),
    createQuestion("BARS (Behaviorally Anchored Rating Scales) uses:", ["Specific behavioral examples for each rating point", "Adjectives only", "Numbers only", "Pass/Fail"], "Specific behavioral examples for each rating point"),
    createQuestion("MBO involves:", ["Setting goals mutually between manager and employee", "Manager dictating goals", "No goals", "Peer setting goals"], "Setting goals mutually between manager and employee"),
    createQuestion("Forced Distribution creates a:", ["Bell curve (ranking employees)", "Flat line", "Team score", "Random list"], "Bell curve (ranking employees)"),
    createQuestion("The primary purpose of Developmental Appraisal is:", ["Identify training needs and feedback", "Determine salary increase", "Layoffs", "Promotion only"], "Identify training needs and feedback"),
    createQuestion("The Recency Effect occurs when ratings are based on:", ["Performance in the last few weeks/months", "First impressions", "The whole year", "Personality"], "Performance in the last few weeks/months"),
    createQuestion("Contrast Error occurs when:", ["An employee is compared to other employees instead of standards", "Compared to self", "Compared to standard", "Rated randomly"], "An employee is compared to other employees instead of standards"),
    createQuestion("Frame of Reference (FOR) Training is for:", ["Raters/Appraisers to standardize their ratings", "Employees", "Customers", "CEOs"], "Raters/Appraisers to standardize their ratings"),
    createQuestion("Performance Management is:", ["A continuous process of identifying, measuring, and developing performance", "A once-a-year meeting", "Just filling forms", "Firing people"], "A continuous process of identifying, measuring, and developing performance"),
    createQuestion("Key Performance Indicators (KPIs) are:", ["Quantifiable measures of performance", "Vague goals", "Personality traits", "Job titles"], "Quantifiable measures of performance"),
    createQuestion("Behavioral Observation Scale (BOS) counts:", ["Frequency of behaviors", "Quality only", "Results only", "Attendance"], "Frequency of behaviors"),
    createQuestion("Strictness Error is:", ["Rating everyone low", "Rating everyone high", "Rating average", "Rating based on mood"], "Rating everyone low"),
    createQuestion("Which appraisal method is best for legal defensibility?", ["BARS / Objective based", "Trait based", "Graphic Rating Scale (Subjective)", "Ranking"], "BARS / Objective based"),

    // 4. Organizational Theories & Behavior (Approx 15)
    createQuestion("Theory of Scientific Management (Taylorism) focuses on:", ["Efficiency and 'One Best Way'", "Human relations", "Bureaucracy", "Systems"], "Efficiency and 'One Best Way'"),
    createQuestion("Weber's Bureaucracy emphasizes:", ["Hierarchy, rules, and impersonality", "Friendship", "Creativity", "Chaos"], "Hierarchy, rules, and impersonality"),
    createQuestion("The Hawthorne Effect showed that:", ["Behavior changes when people know they are being observed", "Lights affect productivity", "Money is the only motivator", "Breaks are bad"], "Behavior changes when people know they are being observed"),
    createQuestion("McGregor's Theory X assumes employees:", ["Dislike work and need control", "Love work", "Are creative", "Are self-motivated"], "Dislike work and need control"),
    createQuestion("McGregor's Theory Y assumes employees:", ["Are self-motivated and seek responsibility", "Hate work", "Need punishment", "Are lazy"], "Are self-motivated and seek responsibility"),
    createQuestion("Herzberg's Two-Factor Theory asserts that:", ["Hygiene factors prevent dissatisfaction; Motivators cause satisfaction", "Money motivates everything", "Needs are hierarchical", "Goals must be hard"], "Hygiene factors prevent dissatisfaction; Motivators cause satisfaction"),
    createQuestion("According to Herzberg, Pay is a:", ["Hygiene Factor", "Motivator", "Growth Factor", "Internal reward"], "Hygiene Factor"),
    createQuestion("Equity Theory (Adams) involves comparing:", ["Inputs/Outcomes ratio with a referent other", "Salary only", "Effort only", "Boss's mood"], "Inputs/Outcomes ratio with a referent other"),
    createQuestion("Expectancy Theory (Vroom) formula:", ["Motivation = Expectancy x Instrumentality x Valence", "M = E x I + V", "M = E / I", "M = V x I"], "Motivation = Expectancy x Instrumentality x Valence"),
    createQuestion("Goal Setting Theory states goals should be:", ["SMART (Specific, Measurable, etc.)", "Vague", "Do your best", "Easy"], "SMART (Specific, Measurable, etc.)"),
    createQuestion("Instrumentality in Vroom's theory is:", ["Belief that performance leads to reward", "Belief that effort leads to performance", "Value of reward", "Confidence"], "Belief that performance leads to reward"),
    createQuestion("Organizational Citizenship Behavior (OCB) is:", ["Discretionary behavior that helps the org but is not required", "Doing the bare minimum", "Following orders", "Leading a team"], "Discretionary behavior that helps the org but is not required"),
    createQuestion("Job Satisfaction is:", ["A positive emotional state resulting from job appraisal", "Performance", "Productivity", "Attendance"], "A positive emotional state resulting from job appraisal"),
    createQuestion("Cognitive Dissonance in the workplace refers to:", ["Incompatibility between two attitudes or behavior", "Low IQ", "Hearing loss", "Agreement"], "Incompatibility between two attitudes or behavior"),
    createQuestion("Continuance Commitment is based on:", ["Cost of leaving (Need to stay)", "Emotional attachment (Want to stay)", "Obligation (Ought to stay)", "Fear"], "Cost of leaving (Need to stay)"),

    // 5. Leadership & Org Development (Approx 15)
    createQuestion("Transformational Leadership focuses on:", ["Inspiring and changing followers", "Clarifying roles and rewards", "Punishment", "Maintaining status quo"], "Inspiring and changing followers"),
    createQuestion("Transactional Leadership focuses on:", ["Exchanges (Rewards for Performance)", "Vision", "Charisma", "Inspiration"], "Exchanges (Rewards for Performance)"),
    createQuestion("Fiedler's Contingency Model says leadership effectiveness depends on:", ["Leader style and situational control", "Only leader traits", "Only followers", "Economy"], "Leader style and situational control"),
    createQuestion("LMX (Leader-Member Exchange) Theory focuses on:", ["Quality of dyadic relationships (In-group vs Out-group)", "Traits", "Groups as a whole", "Culture"], "Quality of dyadic relationships (In-group vs Out-group)"),
    createQuestion("Servant Leadership emphasizes:", ["Serving the needs of others/followers first", "Being a slave", "Command and control", "Profit first"], "Serving the needs of others/followers first"),
    createQuestion("Organizational Development (OD) is:", ["Planned, system-wide change", "Random change", "Training only", "Firing staff"], "Planned, system-wide change"),
    createQuestion("Lewin's Change Model steps:", ["Unfreeze, Change (Move), Refreeze", "Plan, Do, Check", "Analyze, Design, Develop", "Start, Stop, Continue"], "Unfreeze, Change (Move), Refreeze"),
    createQuestion("Appreciative Inquiry focuses on:", ["Positive aspects and strengths of the org", "Problems", "Weaknesses", "Failures"], "Positive aspects and strengths of the org"),
    createQuestion("Groupthink is:", ["Priority on consensus over realistic appraisal", "Good teamwork", "Brainstorming", "Critical thinking"], "Priority on consensus over realistic appraisal"),
    createQuestion("Social Loafing is:", ["Exerting less effort in a group than when alone", "Working harder in a group", "Socializing", "Networking"], "Exerting less effort in a group than when alone"),
    createQuestion("Organizational Culture is:", ["Shared values, beliefs, and norms", "The building", "The rules", "The logo"], "Shared values, beliefs, and norms"),
    createQuestion("Which power base comes from expertise?", ["Expert Power", "Legitimate Power", "Reward Power", "Coercive Power"], "Expert Power"),
    createQuestion("Which power base comes from position/title?", ["Legitimate Power", "Referent Power", "Expert Power", "Reward Power"], "Legitimate Power"),
    createQuestion("Span of Control refers to:", ["Number of subordinates reporting to a manager", "Length of time in the job", "Office size", "Budget limit"], "Number of subordinates reporting to a manager"),
    createQuestion("Matrix Structure involves:", ["Dual reporting lines (Functional and Project)", "Single chain of command", "No bosses", "Virtual teams"], "Dual reporting lines (Functional and Project)"),

    // 6. Emerging Trends & Issues (Global/AI/Wellness) (Approx 20)
    createQuestion("Technostress refers to:", ["Stress caused by working with technology", "Stress about robots", "Coding errors", "Hardware failure"], "Stress caused by working with technology"),
    createQuestion("Work-Life Balance is increasingly being replaced by the concept of:", ["Work-Life Integration", "Work-Life Separation", "Work Addiction", "No Work"], "Work-Life Integration"),
    createQuestion("Which facilitates successful Remote Work?", ["Trust and output-based management", "Micromanagement", "Tracking keystrokes", "Mandatory office days"], "Trust and output-based management"),
    createQuestion("Gig Economy refers to:", ["Short-term contracts/freelance work", "Music industry", "Big corporations", "Government jobs"], "Short-term contracts/freelance work"),
    createQuestion("Emotional Intelligence (EI) in leadership is:", ["Ability to perceive and manage emotions", "IQ", "Technical skill", "Math skill"], "Ability to perceive and manage emotions"),
    createQuestion("Diversity and Inclusion (D&I) initiatives aim to:", ["Create specific value for diverse talents and fair treatment", "Meet quotas only", "Avoid lawsuits only", "Generate PR"], "Create specific value for diverse talents and fair treatment"),
    createQuestion("Psychological Safety (Google project Aristotle) allows teams to:", ["Take risks without fear of punishment", "Be lazy", "Avoid work", "Complain"], "Take risks without fear of punishment"),
    createQuestion("Job Crafting allows employees to:", ["Redesign their job to fit their strengths/interests", "Quit", "Ask for a raise", "Copy others"], "Redesign their job to fit their strengths/interests"),
    createQuestion("The impact of AI in recruitment raises concerns about:", ["Algorithmic Bias", "Speed", "Cost", "Availability"], "Algorithmic Bias"),
    createQuestion("Occupational Health Psychology focuses on:", ["Health and safety of workers", "Clinical therapy", "Recruitment", "Payroll"], "Health and safety of workers"),
    createQuestion("Burnout consists of Exhaustion, Cynicism/Depersonalization, and:", ["Inefficacy (Low personal accomplishment)", "Anxiety", "Anger", "Hunger"], "Inefficacy (Low personal accomplishment)"),
    createQuestion("Cross-Cultural Psychology in IO helps with:", ["Expatriate management and global teams", "Domestic hiring", "Local laws", "Payroll"], "Expatriate management and global teams"),
    createQuestion("Whistleblowing is:", ["Reporting unethical/illegal activities", "Playing sports", "Stopping work", "Cheering"], "Reporting unethical/illegal activities"),
    createQuestion("Ergonomics ensures:", ["Fit between the worker and the work environment/tools", "Desk is expensive", "Chair is blue", "Office is big"], "Fit between the worker and the work environment/tools"),
    createQuestion("Presenteeism is:", ["Being at work but not fully functioning (e.g. sick)", "Being absent", "Being early", "Working late"], "Being at work but not fully functioning (e.g. sick)"),
    createQuestion("Quiet Quitting refers to:", ["Doing only what is required and no more (setting boundaries)", "Resigning secretly", "Leaving early", "Not speaking"], "Doing only what is required and no more (setting boundaries)"),
    createQuestion("Corporate Social Responsibility (CSR) is:", ["Business self-regulation for social good", "Marketing", "Charity only", "Taxes"], "Business self-regulation for social good"),
    createQuestion("Agile Methodology in HR emphasizes:", ["Flexibility, speed, and iteration", "Rigid planning", "Documentation", "Hierarchy"], "Flexibility, speed, and iteration"),
    createQuestion("People Analytics involves using:", ["Data to make people-related decisions", "Guesswork", "Gut feeling", "Tradition"], "Data to make people-related decisions"),
    createQuestion("The 'Right to Disconnect' laws refer to:", ["Right to not answer work emails after hours", "Right to quit", "Right to have no internet", "Right to breaks"], "Right to not answer work emails after hours"),
];

export const ioPsychMarketplaceItem: MarketplaceItem = {
    id: 'io-psych-100',
    title: 'Industrial-Organizational Psychology Mastery (100 Items)',
    description: 'Comprehensive 100-item reviewer for IO Psychology. Covers Recruitment, Training, Org Dev, and modern trends like AI & Remote Work.',
    category: 'Education',
    author: 'Cerebrum Master',
    downloads: 70,
    rating: 4.8,
    price: 'Premium',
    content: shuffleArray(ioPsychQuestions)
};
