import { MarketplaceItem } from './data';
import { QuizQuestion } from '@/types/quiz';
import { shuffleArray } from '@/utils/shuffle';

const createQuestion = (q: string, opts: string[], ans: string): QuizQuestion => ({
    question: q,
    options: opts,
    answer: ans,
    type: 'multiple',
});

const psychAssessmentQuestions: QuizQuestion[] = [
    // 1. Test Construction & General Assessment (approx 20)
    createQuestion("Which of the following best describes a Table of Specifications (TOS)?", ["A list of students taking the exam", "A blueprint for the test content and cognitive levels", "A statistical analysis of test results", "A set of ethical guidelines"], "A blueprint for the test content and cognitive levels"),
    createQuestion("In item writing, what is the 'distractor'?", ["The correct answer", "An incorrect option designed to attract less knowledgeable examinees", "The stem of the question", "The instructions for the test"], "An incorrect option designed to attract less knowledgeable examinees"),
    createQuestion("What is the primary purpose of psychological assessment?", ["To label individuals", "To predict future behavior or outcomes", "To gather data for decision making", "To provide therapy"], "To gather data for decision making"),
    createQuestion("Which scaling method involves absolute zero?", ["Nominal", "Ordinal", "Interval", "Ratio"], "Ratio"),
    createQuestion("Likert scales are typically which level of measurement?", ["Nominal", "Ordinal", "Interval", "Ratio"], "Ordinal"),
    createQuestion("Who is considered the 'Father of the Educational and Psychological Test'?", ["Wilhelm Wundt", "James McKeen Cattell", "E.L. Thorndike", "Lewis Terman"], "James McKeen Cattell"), // Note: Cattell coined 'mental test', Thorndike often cited in ed measurement. Let's stick to standard knowledge items.
    createQuestion("The process of 'norming' a test involves:", ["Writing the questions", "Administering the test to a representative sample", "Checking for typos", "Setting the passing score"], "Administering the test to a representative sample"),
    createQuestion("Which type of test creates a scenario for the examinee to perform a task?", ["Paper-and-pencil test", "Performance test", "Projective test", "Objective test"], "Performance test"),
    createQuestion("A test that measures potential for learning a specific skill is an:", ["Achievement test", "Aptitude test", "Intelligence test", "Personality test"], "Aptitude test"),
    createQuestion("Item difficulty is typically represented by the letter:", ["r", "p", "d", "z"], "p"),
    createQuestion("If an item has a p-value of 0.95, it is considered:", ["Very difficult", "Very easy", "Moderately difficult", "Invalid"], "Very easy"),
    createQuestion("The Item Discrimination Index (D) ranges from:", ["0 to 1", "-1 to +1", "0 to 100", "-infinity to +infinity"], "-1 to +1"),
    createQuestion("What does a negative discrimination index indicate?", ["High performers got the item wrong while low performers got it right", "Everyone got it right", "The item is too easy", "The item is perfect"], "High performers got the item wrong while low performers got it right"),
    createQuestion("Speed tests are designed so that:", ["Items are very difficult", "No one can finish in the time limits", "Accuracy is the only measure", "Items vary in difficulty"], "No one can finish in the time limits"),
    createQuestion("Power tests are characterized by:", ["Strict time limits", "Items of increasing difficulty with sufficient time", "Simple items answering speed", "Only checking psychomotor skills"], "Items of increasing difficulty with sufficient time"),
    createQuestion("Which format is BEST for measuring ability to organize and integrate ideas?", ["Multiple Choice", "True/False", "Essay", "Matching Type"], "Essay"),
    createQuestion("The 'Stem' of a multiple-choice item should:", ["Be vague", "Present a single, definite problem", "Be negatively stated", "Give clues to the answer"], "Present a single, definite problem"),
    createQuestion("Which error occurs when a rater gives high ratings on all dimensions due to a general positive impression?", ["Leniency Error", "Halo Effect", "Central Tendency Error", "Contrast Error"], "Halo Effect"),
    createQuestion("Computer-Adaptive Testing (CAT) selects items based on:", ["The examinee's age", "The examinee's previous response", "Random selection", "Alphabetical order"], "The examinee's previous response"),
    createQuestion("A raw score is:", ["The score after statistical adjustment", "The immediate result of scoring a test (e.g., number correct)", "A percentile rank", "A standard score"], "The immediate result of scoring a test (e.g., number correct)"),

    // 2. Reliability (approx 15)
    createQuestion("Reliability refers to:", ["Accuracy", "Consistency", "Meaningfulness", "Utility"], "Consistency"),
    createQuestion("Which method involves administering the same test twice to the same group?", ["Test-Retest", "Alternate Forms", "Split-Half", "Inter-rater"], "Test-Retest"),
    createQuestion("Test-Retest reliability measures:", ["Internal consistency", "Stability over time", "Equivalence of forms", "Scorer consistency"], "Stability over time"),
    createQuestion("Which coefficient represents internal consistency?", ["Pearson r", "Spearman Rho", "Cronbach's Alpha", "Cohen's Kappa"], "Cronbach's Alpha"),
    createQuestion("Split-half reliability is often corrected using which formula?", ["Pearson-Product Moment", "Spearman-Brown Prophecy Formula", "Kuder-Richardson 20", "Chi-Square"], "Spearman-Brown Prophecy Formula"),
    createQuestion("Inter-rater reliability is most crucial for:", ["Multiple choice tests", "Projective tests or Essays", "Speed tests", "Computerized tests"], "Projective tests or Essays"),
    createQuestion("Standard Error of Measurement (SEM) is used to calculate:", ["Content validity", "Confidence intervals around a score", "Item difficulty", "Norms"], "Confidence intervals around a score"),
    createQuestion("If validity is high, reliability is usually:", ["Low", "High", "Zero", "Unknown"], "High"),
    createQuestion("Can a test be reliable but not valid?", ["Yes", "No", "Only in projective tests", "Only in intelligence tests"], "Yes"),
    createQuestion("Which factor usually increases reliability?", ["Fewer items", "More items", "Heterogeneous group", "Subjective scoring"], "More items"),
    createQuestion("KR-20 is used for items that are:", ["Dichotomous (Right/Wrong)", "Polytomous (Likert)", "Open-ended", "Weighted"], "Dichotomous (Right/Wrong)"),
    createQuestion("Coefficient Alpha is appropriate for:", ["Dichotomous items only", "Items with multiple scoring possibilities (e.g., Likert)", "Speed tests", "Test-retest"], "Items with multiple scoring possibilities (e.g., Likert)"),
    createQuestion("The main source of error in Test-Retest reliability is:", ["Content sampling", "Time sampling", "Inter-scorer differences", "Item sampling"], "Time sampling"),
    createQuestion("Reliability coefficient of .90 indicates:", ["90% of variance is due to error", "10% of variance is due to error", "The test is valid", "The test is perfect"], "10% of variance is due to error"),
    createQuestion("Alternate-Forms reliability controls for:", ["Practice effects", "Time sampling error only", "Content sampling error", "Scorer error"], "Practice effects"),

    // 3. Validity (approx 15)
    createQuestion("Validity asks the question:", ["Are the results consistent?", "Does the test measure what it purports to measure?", "Is the test fair?", "are the norms updated?"], "Does the test measure what it purports to measure?"),
    createQuestion("Content validity is primarily determined by:", ["Statistical analysis", "Expert judgment", "Correlation with other tests", "Factor analysis"], "Expert judgment"),
    createQuestion("Face validity refers to:", ["Statistical validity", "Superficial appearance of the test", "Concurrent validity", "Predictive power"], "Superficial appearance of the test"),
    createQuestion("Construct validity includes which two types?", ["Internal and External", "Convergent and Divergent", "Predictive and Concurrent", "Face and Content"], "Convergent and Divergent"),
    createQuestion("Convergent validity is shown when:", ["A test correlates high with a test measuring a similar construct", "A test correlates low with a test measuring a different construct", "A test predicts future performance", "Experts agree on content"], "A test correlates high with a test measuring a similar construct"),
    createQuestion("Divergent (Discriminant) validity is shown when:", ["A test correlates high with a similar test", "A test correlates low with a theoretically unrelated test", "A test predicts a criterion", "A test has high reliability"], "A test correlates low with a theoretically unrelated test"),
    createQuestion("Concurrent validity is a type of:", ["Content Validity", "Criterion-Related Validity", "Construct Validity", "Face Validity"], "Criterion-Related Validity"),
    createQuestion("In predictive validity, the 'criterion' is measured:", ["At the same time as the test", "At a later time", "Before the test", "During item analysis"], "At a later time"),
    createQuestion("Factor Analysis is a statistical technique often used for:", ["Content Validity", "Construct Validity", "Reliability", "Item Analysis"], "Construct Validity"),
    createQuestion("Standard Error of Estimate (SEE) is associated with:", ["Reliability", "Validity (Prediction)", "Item Difficulty", "Mean calculation"], "Validity (Prediction)"),
    createQuestion("A table of specifications helps ensure:", ["Construct Validity", "Content Validity", "Predictive Validity", "Concurrent Validity"], "Content Validity"),
    createQuestion("If a test discriminates between clinical and normal populations as expected, it shows:", ["Known-groups validity (Construct)", "Face validity", "Reliability", "Split-half"], "Known-groups validity (Construct)"),
    createQuestion("The 'validity coefficient' is usually a:", ["Mean score", "Standard deviation", "Correlation coefficient", "Z-score"], "Correlation coefficient"),
    createQuestion("Which is more important generally?", ["Reliability", "Validity", "They are equal", "Dependability"], "Validity"),
    createQuestion("Multitrait-Multimethod Matrix is used to check:", ["Construct Validity", "Content Validity", "Reliability", "Norms"], "Construct Validity"),

    // 4. Statistics (approx 25)
    createQuestion("Measure of central tendency most affected by extreme scores:", ["Mode", "Median", "Mean", "Range"], "Mean"),
    createQuestion("The middle score in a distribution:", ["Mode", "Median", "Mean", "Variance"], "Median"),
    createQuestion("The most frequent score:", ["Mode", "Median", "Mean", "Standard Deviation"], "Mode"),
    createQuestion("In a normal distribution, the Mean, Median, and Mode are:", ["Different", "Equal", "Unrelated", "Negative"], "Equal"),
    createQuestion("Total area under the normal curve is:", ["50%", "100%", "95%", "99%"], "100%"),
    createQuestion("Approximately what percentage of scores falls between -1 SD and +1 SD?", ["50%", "68%", "95%", "99%"], "68%"),
    createQuestion("A Z-score has a mean of __ and SD of __.", ["0, 1", "50, 10", "100, 15", "10, 2"], "0, 1"),
    createQuestion("A T-score has a mean of __ and SD of __.", ["0, 1", "50, 10", "100, 15", "500, 100"], "50, 10"),
    createQuestion("If a raw score is exactly at the mean, the Z-score is:", ["1", "0", "-1", "50"], "0"),
    createQuestion("A correlation coefficient of -0.85 indicates:", ["Weak negative relationship", "Strong negative relationship", "Strong positive relationship", "No relationship"], "Strong negative relationship"),
    createQuestion("Coefficient of Determination (r squared) tells us:", ["Direction of relationship", "Percent of variance shared", "Significance level", "Standard deviation"], "Percent of variance shared"),
    createQuestion("Type I Error is:", ["Rejecting a true null hypothesis", "Accepting a false null hypothesis", "Calculation error", "Sampling error"], "Rejecting a true null hypothesis"),
    createQuestion("Type II Error is:", ["Rejecting a true null hypothesis", "Failing to reject a false null hypothesis", "Scoring error", "Standard error"], "Failing to reject a false null hypothesis"),
    createQuestion("The scale used for rank-ordering data:", ["Nominal", "Ordinal", "Interval", "Ratio"], "Ordinal"),
    createQuestion("Which scale allows for addition and subtraction but multiplying is meaningless (no true zero)?", ["Nominal", "Ordinal", "Interval", "Ratio"], "Interval"),
    createQuestion("Percentile Rank describes:", ["Percentage of items correct", "Percentage of people scoring below a certain raw score", "Percentage of people scoring above", "Grade equivalent"], "Percentage of people scoring below a certain raw score"),
    createQuestion("Stanine scale ranges from:", ["1 to 9", "1 to 10", "1 to 5", "0 to 100"], "1 to 9"),
    createQuestion("Positive Skew indicates:", ["Tail points to the right (high scores)", "Tail points to the left", "Symmetric", "Bimodal"], "Tail points to the right (high scores)"),
    createQuestion("Kurtosis refers to:", ["Skewness", "Peakedness or flatness of a distribution", "Central tendency", "Dispersion"], "Peakedness or flatness of a distribution"),
    createQuestion("Leptokurtic distribution is:", ["Flat", "Peaked", "Normal", "Skewed"], "Peaked"),
    createQuestion("Platykurtic distribution is:", ["Flat", "Peaked", "Normal", "Skewed"], "Flat"),
    createQuestion("The variance is the square of the:", ["Mean", "Median", "Standard Deviation", "Range"], "Standard Deviation"),
    createQuestion("Criterion-referenced interpretation compares performance to:", ["A norm group", "A standard or mastery level", "Previous performance", "Other students"], "A standard or mastery level"),
    createQuestion("Norm-referenced interpretation compares performance to:", ["A norm group", "A standard", "An absolute criteria", "The teacher's expectation"], "A norm group"),
    createQuestion("Deviation IQ is a type of:", ["Standard Score", "Raw Score", "Percentile", "Age Equivalent"], "Standard Score"),

    // 5. Ethics & Philippine Psychology Act (approx 25)
    createQuestion("The Philippine Psychology Act of 2009 is:", ["RA 10029", "RA 9258", "RA 11036", "RA 7610"], "RA 10029"),
    createQuestion("Psychometricians are authorized to administer:", ["Level A, B, and C tests independently", "Level A and B tests; Level C under supervision", "Only Level A tests", "All tests without supervision"], "Level A and B tests; Level C under supervision"),
    createQuestion("Test data (raw scores, protocols) should be released to:", ["The client immediately", "The referral source only", "Only to qualified professionals/Psychologists", "Anyone who pays"], "Only to qualified professionals/Psychologists"),
    createQuestion("Confidentiality can be breached when:", ["The client is boring", "There is imminent danger to self or others", "The employer asks for it", "Never"], "There is imminent danger to self or others"),
    createQuestion("Informed Consent MUST be obtained:", ["After testing", "Before assessment begins", "Only for children", "Only for research"], "Before assessment begins"),
    createQuestion("Who owns the physical test record?", ["The client", "The institution/psychologist", "The court", "The test publisher"], "The institution/psychologist"),
    createQuestion("Test security means:", ["Keeping test content/materials restricted to qualified users", "Locking the office", "Password protecting reports", "Not telling the client the results"], "Keeping test content/materials restricted to qualified users"),
    createQuestion("If a test is obsolete (outdated), a Psychometrician should:", ["Use it anyway", "Avoid using it for current evaluation", "Update it personally", "Sell it"], "Avoid using it for current evaluation"),
    createQuestion("Which principle mandates maximizing benefit and minimizing harm?", ["Integrity", "Beneficence and Non-maleficence", "Justice", "Respect for Rights"], "Beneficence and Non-maleficence"),
    createQuestion("Multiple relationships should be avoided if they:", ["Impair objectivity or harm the client", "Are convenient", "Are profitable", "Are friendly"], "Impair objectivity or harm the client"),
    createQuestion("When assessing a client from a different culture, the Psychometrician must:", ["Use standard norms", "Be aware of cultural limitations and bias", "Ignore culture", "Translate the test literally"], "Be aware of cultural limitations and bias"),
    createQuestion("A Psychometrician can sign a psychological report:", ["Ideally prepared by them, but approved/supervised by a Psychologist", "Independently for psychopathologies", "Only for industrial settings independently", "Never"], "Ideally prepared by them, but approved/supervised by a Psychologist"),
    createQuestion("The validity of assessment results typically expires after:", ["1 month", "6 months to 1 year (typically 2 years for validity of findings)", "10 years", "Forever"], "6 months to 1 year (typically 2 years for validity of findings)"), // Generalized acceptable answer for board
    createQuestion("Who is responsible for the appropriate use of a test?", ["The manufacturer", "The test user / administrator", "The client", "The printer"], "The test user / administrator"),
    createQuestion("Assessment Feedback is:", ["Optional", "A right of the client", "Only for the doctor", "Not necessary"], "A right of the client"),
    createQuestion("Level A tests are:", ["Tests that require advanced training", "Tests that can be administered with general orientation (e.g., achievement tests)", "Projective tests", "Intelligence tests"], "Tests that can be administered with general orientation (e.g., achievement tests)"),
    createQuestion("Level B tests require:", ["Doctorate degree", "Technical knowledge of test construction and use (e.g., aptitude tests, personality inventories)", "No training", "Medical license"], "Technical knowledge of test construction and use (e.g., aptitude tests, personality inventories)"),
    createQuestion("Level C tests require:", ["Substantial understanding of testing and supporting psychological fields (requires supervision for Psychometricians)", "Bachelor's degree only", "High school diploma", "General orientation"], "Substantial understanding of testing and supporting psychological fields (requires supervision for Psychometricians)"),
    createQuestion("Deception in research/assessment is allowed:", ["Never", "Only when justified by value and no alternative is available", "Whenever needed", "To make it fun"], "Only when justified by value and no alternative is available"),
    createQuestion("If a client cannot afford services:", ["Turn them away immediately", "Make appropriate referral", "Do it for free always", "Report them"], "Make appropriate referral"),
    createQuestion("Psychometricians must renew their license every:", ["1 year", "2 years", "3 years", "5 years"], "3 years"),
    createQuestion("CPD stands for:", ["Continuing Professional Development", "Clinical Psychology Department", "Central Processing Data", "Career Planning Development"], "Continuing Professional Development"),
    createQuestion("Sexual intimacies with current therapy clients/assessment clients are:", ["Allowed after 6 months", "Strictly prohibited", "Allowed if consensual", "Allowed if reported"], "Strictly prohibited"),
    createQuestion("Test developers must provide:", ["The answers to the public", "Manuals describing norms, reliability, and validity", "Free copies", "Training for everyone"], "Manuals describing norms, reliability, and validity"),
    createQuestion("Which is a violation of test security?", ["Coaching examinees on specific test items", "Teaching general test-taking strategies", "Explaining the purpose of the test", "Providing a quiet environment"], "Coaching examinees on specific test items"),
];

export const psychAssessmentMarketplaceItem: MarketplaceItem = {
    id: 'psych-assess-100',
    title: 'Psychological Assessment Mastery (100 Items)',
    description: 'Comprehensive 100-item practice test for Psychological Assessment. Covers Test Construction, Reliability, Validity, Statistics, and Ethics.',
    category: 'Education',
    author: 'Cerebrum Master',
    downloads: 80,
    rating: 4.9,
    price: 'Premium',
    content: shuffleArray(psychAssessmentQuestions)
};
